name: Build and Test Python Client-Server

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Server in Background
      run: |
        python server.py &
      shell: bash

    - name: Run Client Test
      run: python client.py

    - name: Cleanup
      run: |
        pkill -f server.py || true
        pkill -f client.py || true
      shell: bash

